Create a FuseBox class to group multiple breakers
screwdriver-cd/circuit-fuses pull request #15
Opened 2017-08-07 21:37 UTC by pranavrc

Use case: To create multiple circuit breakers with different settings and group them into one 'fusebox' so they can all be tripped if one breaks.

2017-08-07 21:45 UTC, stjohnjohnson requested changes
This is a breaking change.  Please bump the major version.

2017-08-07 21:54 UTC, yahoocla commented
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

2017-08-07 21:54 UTC, FenrirUnbound commented
I can't think of a scenario where one would need to trip other circuit breakers if a different one is tripped. What case would you apply this usage for?

2017-08-07 21:57 UTC, pranavrc commented
@FenrirUnbound We need to create a circuit breakers with specific timeouts for each jenkins API endpoint but we'd have to bind them all into a single cluster so that if one breaks, we trip all endpoints across the same cluster.

2017-08-07 22:02 UTC, tkyi commented
This repository is using semantic release, so you'll need to add `BREAKING CHANGES` in your commit message somewhere in order to bump major version. You can leave the package.json as it was before.
(http://docs.screwdriver.cd/about/contributing#submitting-pull-requests)

2017-08-07 23:16 UTC, petey requested changes

2017-08-07 23:16 UTC, petey commented on test/index.test.js
> +            assert.equal(breaker1.isClosed(), true);
`assert.isTrue()`

2017-08-07 23:16 UTC, petey commented on test/index.test.js
> +            assert.equal(breaker1.isClosed(), false);
`assert.isFalse()`

2017-08-07 23:16 UTC, petey commented on index.js
> +class FuseBox {
missing jsdoc

2017-08-07 23:16 UTC, petey commented on index.js
> +    createFuse(command, options) {
missing jsdoc and tests

2017-08-07 23:16 UTC, petey commented on index.js
> +    addFuse(breaker) {
missing jsdoc

2017-08-07 23:16 UTC, petey commented on index.js
> +    tripFuses() {
missing jsdoc and tests

2017-08-07 23:16 UTC, petey commented on index.js
> +        breaker.breaker.on('open', () => self.tripFuses());
This is giving me a bad code smell. I feel like this is tying into something that should be a private api. CircuitBreaker should probably expose the events of its implementation directly.

2017-08-07 23:16 UTC, petey commented on index.js
> +     * @method constructor
missing `@constructor`

2017-08-07 23:21 UTC, FenrirUnbound approved these changes
👍 

Seems fine to me

![htkzv0ciacez](https://user-images.githubusercontent.com/721148/29049700-63b9b1e0-7b8c-11e7-961e-acee2c7d6be8.gif)

2017-08-08 05:30 UTC, stjohnjohnson requested changes

2017-08-08 05:30 UTC, stjohnjohnson commented on index.js
> +    createFuse(command, options) {
Why is there a `createFuse` and `addFuse`?

2017-08-08 05:30 UTC, stjohnjohnson commented on index.js
> +module.exports = {
Please update the `README` to describe the new features as well as how to integrate with the old features (since the interface changed).

2017-08-08 20:06 UTC, petey approved these changes
The electrical engineer in me says that the fusebox analogy doesn't really hold up very well, but the code seems sound.

2017-08-09 00:11 UTC, stjohnjohnson approved these changes

2017-08-09 00:11 UTC, stjohnjohnson commented on README.md
> +const fusebox = new FuseBox();
This is valid but insane.

2017-08-09 00:14 UTC, pranavrc commented on README.md
> +const fusebox = new FuseBox();
<insert link to wat.talk>

2017-08-09 00:17 UTC, merged